spring.application.name=api-gateway
server.port=8765

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service-lower
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[1].id=auth-service-upper
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/AUTH-SERVICE/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[2].id=patient-service-lower
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/patient-service/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[3].id=patient-service-upper
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://PATIENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/PATIENT-SERVICE/**
spring.cloud.gateway.server.webmvc.routes[3].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[4].id=doctor-service-lower
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/doctor-service/**
spring.cloud.gateway.server.webmvc.routes[4].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[5].id=doctor-service-upper
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://DOCTOR-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/DOCTOR-SERVICE/**
spring.cloud.gateway.server.webmvc.routes[5].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[6].id=appointment-service-lower
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/appointment-service/**
spring.cloud.gateway.server.webmvc.routes[6].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[7].id=appointment-service-upper
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://APPOINTMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/APPOINTMENT-SERVICE/**
spring.cloud.gateway.server.webmvc.routes[7].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[8].id=queue-service-lower
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://QUEUE-SERVICE
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/queue-service/**
spring.cloud.gateway.server.webmvc.routes[8].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webmvc.routes[9].id=queue-service-upper
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://QUEUE-SERVICE
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/QUEUE-SERVICE/**
spring.cloud.gateway.server.webmvc.routes[9].filters[0]=StripPrefix=1

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

app.jwt.secret=ThisIsMySuperSecretKeyForJwtSigning12345678901234567890
